CREATE DATABASE IF NOT EXISTS fang_data
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE fang_data;

CREATE TABLE IF NOT EXISTS fang_listing (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  url VARCHAR(512) NOT NULL,
  title VARCHAR(255) NULL,
  price VARCHAR(64) NULL,
  description TEXT NULL,
  crawled_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_url (url)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
